
import { GoogleGenAI } from "@google/genai";
import { GEMINI_MODEL } from "../constants";

export const processRepaint = async (base64Image: string, colorName: string, colorHex: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // Clean up base64 prefix if present
  const base64Data = base64Image.split(',')[1] || base64Image;
  const mimeType = base64Image.includes('image/png') ? 'image/png' : 'image/jpeg';

  const prompt = `
    You are an expert interior designer. 
    Look at the provided image. Identify the large wall in the background (which may have some water damage, patches, or uneven textures).
    
    Repaint ONLY this specific wall to a beautiful, professional finish using the color: ${colorName} (${colorHex}).
    
    CRITICAL INSTRUCTIONS:
    1. Keep all furniture, lighting fixtures (like the track lights), curtains, bedding, and outlets EXACTLY as they are.
    2. The new paint should look realistic, following the shadows and lighting conditions of the original room.
    3. Make the wall surface look smooth and freshly painted, effectively "repairing" any visible damage or patches in the image.
    4. Do not change the color of the ceiling or adjacent walls if they are separate planes.
    5. Return ONLY the edited image.
  `;

  try {
    const response = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:${mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image was generated by the AI.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
